---
# tasks file for puppet
- name: Roles de Instalação do Puppet-agent
  hosts: all
  tasks:
    - include: prerequisitos.yml
    - include: install_ubuntu.yml
      when: ansible_distribution == "Ubuntu"
    - include: install_centos.yml
      when: ansible_distribution == "CentOS"
