---
- name: instalando GITLAB
  hosts: devops
  tasks:
    - name: instalando pacotes necessários
      apt:
        name: ['curl','openssh-server','ca-certificates']
        state: present
        update-cache: yes

    - name: executando script - GITLAB
      shell:  curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash
      register: comando

    - name: instalando pacote - GITLAB
      apt:
        name: gitlab-ce
        state: present
      when: comando.rc == 0
